[package]
name = "aumentada"
version = "0.1.0"
edition = "2021"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

[dependencies]
rand = "0.8"
bottomify = "1.2.0"

[dependencies.neon]
version = "0.9"
default-features = false
features = ["napi-6"]
